name: Deploy Function App

on:
  push:
    branches: [main]
    paths:
      - 'server/**'

jobs:
  deploy-function:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Install Dependencies
        run: |
          cd server
          npm ci

      - name: Zip Function App
        run: |
          cd server
          zip -r ../function.zip . -x "*.git*" "*.node_modules/*" "node_modules/*" "local.settings.json" ".vscode/*" "src/*"

      - name: Test Zip File
        run: |
          ls -la ../function.zip

      - name: Deploy Function App
        run: |
          az login --service-principal --username ${{ secrets.AZURE_CLIENT_ID }} --password ${{ secrets.AZURE_CLIENT_SECRET }} --tenant ${{ secrets.AZURE_TENANT_ID }}
          az webapp deployment source config-zip \
            --name ${{ secrets.FUNCTION_APP_NAME }} \
            --resource-group ${{ secrets.RESOURCE_GROUP_NAME }} \
            --src ../function.zip

      - name: Check Function List
        run: |
          az functionapp list --resource-group ${{ secrets.RESOURCE_GROUP_NAME }} --query "[].name" --output table